name: d_unit_project
repository: https://github.com/amondnet/auto_test

packages:
  - packages/**
ignore:
  - "packages/**/example"
  - packages/flutter_example
  - packages/asserts
  - packages
ide:
  intellij: true

sdkPath: .fvm/flutter_sdk

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
    select-package:
      ignore:
        - "*monorepo*"

  test:
    description: Run tests in a specific package.
    run: melos exec --concurrency=1 -- "dart pub get && dart test --reporter expanded"
    select-package:
      depends-on: "test"
      dir-exists:
        - "test/"

  test:coverage:
    description: Run tests in a specific package.
    run: melos exec --concurrency=1 -- "dart pub get  && dart run test --coverage=./coverage test/full_coverage_test.dart"
    select-package:
      depends-on: "test"
      dir-exists:
        - "test/"

  format: dart format -o write .
  version: dart run scripts/generate_version.dart
