name: auto_test
description: Support for discovering tests and test suites using reflection.
version: 0.1.0
homepage: https://github.com/amondnet/auto_test

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
