name: auto_test
description: Support for discovering tests and test suites using reflection.
version: 0.1.0+1
homepage: https://github.com/amondnet/auto_test

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: '>=1.16.0 <2.0.0'

dev_dependencies:
  lints: ^1.0.0
  test_coverage: