name: auto_test
description: Support for discovering tests and test suites using reflection.
version: 0.2.1
homepage: https://github.com/amondnet/auto_test

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  test: '>=1.16.0 <2.0.0'
  reflectable: ^4.0.0
  uuid:
dev_dependencies:
  lints: ^2.0.0