name: asserts
description: Fluent Assertions for dart.
version: 0.0.1
homepage: https://github.com/amondnet/auto_test/packages/assert

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: '>=1.16.0 <2.0.0'

dev_dependencies:
  lints: ^1.0.0
  test_coverage: