name: flutter_auto_test
description: Support for discovering tests and test suites using reflection.
version: 0.1.4
homepage: https://github.com/amondnet/auto_test

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  test_api: '>=0.4.0 <1.0.0'
  reflectable: ^4.0.0
dev_dependencies:
  test:
  lints: ^2.0.0
  build_runner:
  build_test: any
